import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import AuthWrapper from "@/components/authWrapper";
import LayoutContent from "@/components/layoutContent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Medicine Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthWrapper>
          <LayoutContent>
            {children}
          </LayoutContent>
        </AuthWrapper>
      </body>
    </html>
  );
}
