import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import Footer from "@/partials/footer";
import Menu from "@/partials/menu";
import Header from "@/partials/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin: boolean = true;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isLogin ? (
          <React.Fragment>
            <div className="flex">
              <div className="border p-5 bg-blue-500 text-white font-bold">
                <Menu />
              </div>
              <div className="flex-1">
                <Header />

                <div className="px-5 py-8">
                  {children}
                </div>

                <Footer />
              </div>
            </div>
          </React.Fragment>
        ) : (
          <React.Fragment>
            {children}
          </React.Fragment>
        )}
      </body>
    </html>
  );
}
